name: Build, test and deploy new docker image

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
        with:
          ref: master

      - name: "Login to self hosted docker image registry"
        uses: docker/login-action@v2
        with:
          registry: docker.benevolo.de
          username: docker_admin
          password: ${{secrets.DOCKER_REGISTRY_ACCESS_PASSWORD}}

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17.0
          distribution: oracle
          cache: "maven"

      - name: "Build the maven package"
        run: ACCESS_TOKEN=${{secrets.GH_REGISTRY_ACCESS_PASSWORD}} \
          DE_THI_AZURE_ENDPOINT=https://exentra-eval.cognitiveservices.azure.com/ \
          DE_THI_AZURE_KEY=${{secrets.DE_THI_AZURE_KEY}} \
          mvn -X -s $GITHUB_WORKSPACE/.github/maven/settings.xml -B package --file pom.xml

      - name: "Build and test form-rec image"
        run: |
          docker build -f src/main/docker/Dockerfile.jvm \
          --tag docker.benevolo.de/stiehl-seine-perlen/form-rec:dev .

      - name: "Push form-rec image to self hosted docker image registry"
        run: |
          docker push docker.benevolo.de/stiehl-seine-perlen/form-rec:dev
        # run: |
        # curl -X POST https://portainer.benevolo.de/api/webhooks/3e91d8ec-e40c-4fba-a0c0-9caa002e5262
      #- name: "Deploy new image"
